events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Rota para o Front-end
        location / {
            proxy_pass http://127.0.0;
        }

        # Rota para a API de Usuário
        location /usuario {
            proxy_pass http://127.0.0.1:30002;
        }

        # Rotas para a API de Disciplina
        location /disciplinas { proxy_pass http://127.0.0.1:30001; }
        location /professores { proxy_pass http://127.0.0.1:30001; }
        location /nomeProfessor { proxy_pass http://127.0.0.1:30001; }

        # Rotas para a API de Matrícula
        location /matricula { proxy_pass http://127.0.0.1:30003; }
        location /alunos { proxy_pass http://127.0.0.1:30003; }
        location /nomeAluno { proxy_pass http://127.0.0.1:30003; }
        location /nomeDisciplina { proxy_pass http://127.0.0.1:30003; }
    }
}
