apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sistema-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:

          - path: /usuario
            pathType: Prefix
            backend:
              service:
                name: usuario
                port:
                  number: 3002

          - path: /disciplinas
            pathType: Prefix
            backend:
              service:
                name: disciplina
                port:
                  number: 3001

          - path: /professores
            pathType: Prefix
            backend:
              service:
                name: disciplina
                port:
                  number: 3001

          - path: /nomeProfessor
            pathType: Prefix
            backend:
              service:
                name: disciplina
                port:
                  number: 3001

          - path: /alunos
            pathType: Prefix
            backend:
              service:
                name: matricula
                port:
                  number: 3003

          - path: /matricula
            pathType: Prefix
            backend:
              service:
                name: matricula
                port:
                  number: 3003

          - path: /nomeAluno
            pathType: Prefix
            backend:
              service:
                name: matricula
                port:
                  number: 3003

          - path: /nomeDisciplina
            pathType: Prefix
            backend:
              service:
                name: matricula
                port:
                  number: 3003

          - path: /
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: 8080