apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;

            # Configuração Global de CORS
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'X-Requested-With,Content-Type,Authorization' always;

            # Tratar requisições OPTIONS (Pre-flight)
            if ($request_method = 'OPTIONS') {
                return 204;
            }

            location / {
                proxy_pass http://front:8080;
            }

            location /usuario {
                proxy_pass http://usuario:3002;
            }

            location /disciplinas {
                proxy_pass http://disciplina:3001;
            }

            location /professores {
                proxy_pass http://disciplina:3001;
            }

            location /nomeProfessor {
                proxy_pass http://disciplina:3001;
            }

            location /matricula {
                proxy_pass http://matricula:3003;
            }

            location /alunos {
                proxy_pass http://matricula:3003;
            }

            location /nomeAluno {
                proxy_pass http://matricula:3003;
            }

            location /nomeDisciplina {
                proxy_pass http://matricula:3003;
            }
        }
    }
